### ISSUE TITLE
Error after first toggle

### ISSUE THREAD

**Issue by khalidchawtany** [mcchrish/info-window.nvim#2]
When I show the info window for the second time I get an error with some text.
https://github.com/mcchrish/info-window.nvim/blob/a38531e1e0324af996ba6f45e21773a0b35a2819/autoload/infowindow.vim#L77

The error is:
![Screen Shot 2020-03-30 at 6 26 31 PM](https://user-images.githubusercontent.com/1681606/77930864-1332d680-72b4-11ea-9242-310614abbec7.png)

**Comment by mcchrish** [comment]
That's strange. Does it have something to do with the `echom` line?
I've removed it now https://github.com/mcchrish/info-window.nvim/commit/df23ae8ed939fc565be56b98f46ce18e05e4b34b

**Comment by khalidchawtany** [comment]
The text is gone. However, the error still persists.

![Screen Shot 2020-04-01 at 11 14 25 AM](https://user-images.githubusercontent.com/1681606/78114547-1dff7f80-740a-11ea-8a31-27678e3c52d9.png)

**Comment by mcchrish** [comment]
I see. Can you tell some information about your setup? OS, neovim version etc etc

Edit: btw, I did some updates in how the window and buffer are closed/deleted. `w:history` tells me it might something to do with the window handling.

**Comment by khalidchawtany** [comment]
>Edit: btw, I did some updates in how the window and buffer are closed/deleted. w:history tells me it might something to do with the window handling.

Thanks, it is fixed now.
